# Namespace definition
namespace: cronjob

# Deployment vars
deployment:
  name: unified-api-catalog-dev-services
  replicas: 1
  revisionHistoryLimit: 6
  image: nginx:latest
  #imagePullSecrets:
  #  - unified-api-catalog-dev-cr
  containerPorts:
    - 5000 
  resources:
    limits:
      memory: "512Mi"
      cpu: "250m"
    requests:
      memory: "256Mi"
      cpu: "125m"
  #env:
  #  ASPNETCORE_ENVIRONMENT: "Development"

# Service vars
service:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80

# CronJob Vars
cronjob:
  deploymentName: unified-api-catalog-dev-cronjob
  image: busybox  # Replace with the image you want for the CronJob
  schedule: "*/5 * * * *"  # Every 5 minutes, adjust as needed
  concurrencyPolicy: "Allow"  # Options: Allow, Forbid, Replace
  suspend: false  # Set to true to pause CronJob
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  backoffLimit: 4
  ttlSecondsAfterFinished: 3600  # Time after job finishes before cleanup

# Vault Sidecar secret injection
vault:
  flags:
    vaultAgentInitEnabled: "yes"
  configs:
    kubernetesCluster: "eai-0-centralus-npe"
    vaultServer: "https://preprod.vault.humana.net"  # NPE server for PROD use https://prod.vault.humana.net
    vaultNamespace: "nseai"
    vaultFolder: "unified-api-catalog.app0002181"
    outputFormat: "json"  # OPTIONAL
    logLevel: "info"  # OPTIONAL
    vault.hashicorp.com/ca-cert: '/tls/cabundle.crt'
  secrets:
    - secretFileName: "uac-service.json" 
      secretPath: "/secret/unified-api-catalog.app0002181/uac-service-dev"
    - secretFileName: "vault-metadata.json"
      secretPath: "/secret/unified-api-catalog.app0002181/vault_metadata"
