{{- range $name, $deployment := .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: {{ $deployment.replicas }}
  revisionHistoryLimit: {{ $deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      component: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.namespace }}
        component: {{ $name }}
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: {{ $name }}
          image: {{ $deployment.image }}
          env:
            {{- range $key, $value := $deployment.env }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          ports:
            {{- range $port := $deployment.containerPorts }}
            - containerPort: {{ . }}
            {{- end }}
          resources:
            limits:
              memory: {{ $deployment.resources.limits.memory }}
              cpu: {{ $deployment.resources.limits.cpu }}
            requests:
              memory: {{ $deployment.resources.requests.memory }}
              cpu: {{ $deployment.resources.requests.cpu }}
      imagePullSecrets:
        {{- range $deployment.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
---
{{- end }}
