{{- range $name, $deployment := .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ $name }}  # Using $name for deployment name
  namespace: {{ $.Values.namespace }}  # Using the global namespace value
spec:
  replicas: {{ $deployment.replicas }}
  revisionHistoryLimit: {{ $deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      component: {{ $name }}  # Label component for selector
  template:
    metadata:
      labels:
        app: {{ $.Values.namespace }}
        component: {{ $name }}  # Label component for the pod
      {{- if $deployment.vault.flags.vaultAgentInitEnabled }}
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-init-first: 'true'
        vault.hashicorp.com/preserve-secret-case: 'true'
        vault.hashicorp.com/tls-secret: 'vault-tls-secret'
        vault.hashicorp.com/ca-cert: "/vault/tls/ca-bundle.crt"
        vault.hashicorp.com/log-level: '{{ $deployment.vault.configs.logLevel | default "info" }}'
        vault.hashicorp.com/service: '{{ $deployment.vault.configs.vaultServer }}'
        vault.hashicorp.com/namespace: '{{ $deployment.vault.configs.vaultNamespace }}'
        vault.hashicorp.com/auth-type: 'kubernetes'
        vault.hashicorp.com/auth-path: 'auth/kubernetes/{{ $deployment.vault.configs.kubernetesCluster }}'
        vault.hashicorp.com/role: '{{ $deployment.vault.configs.vaultFolder }}-kubernetes-role'
        vault.hashicorp.com/agent-inject-default-template: '{{ $deployment.vault.configs.outputFormat }}'
        {{- range $deployment.vault.secrets }}
        vault.hashicorp.com/agent-inject-secret-{{ .secretFileName }}: '{{ .secretPath }}'
        vault.hashicorp.com/agent-inject-template-{{ .secretFileName }}: |
          {{`{{ with secret " `}} {{ .secretPath }} {{` " }}} }
          {{`{{ .Data.data | toJSON }}`} }
          {{`{{ end }}}}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: {{ $name }}
          image: {{ $deployment.image }}
          env:
            {{- range $key, $value := $deployment.env }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          ports:
            {{- range $deployment.containerPorts }}
            - containerPort: {{ . }}
            {{- end }}
          resources:
            limits:
              memory: {{ $deployment.resources.limits.memory }}
              cpu: {{ $deployment.resources.limits.cpu }}
            requests:
              memory: {{ $deployment.resources.requests.memory }}
              cpu: {{ $deployment.resources.requests.cpu }}
      imagePullSecrets:
        {{- range $deployment.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
---
{{- end }}
