apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.namespace }}
    component: {{ .Values.deployment.name }}
  ports:
    - name: http
      port: {{ .Values.service.ports[0].port }}
      protocol: {{ .Values.service.ports[0].protocol }}
      targetPort: {{ .Values.service.ports[0].targetPort }}
  type: ClusterIP
