apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.namespace }}
    component: {{ .Values.deployment.name }}
  ports:
    {{- range .Values.service.ports }}
    - name: http
      port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
    {{- end }}
  type: LoadBalancer
